### ISSUE TITLE
Apple M1 silicon installation via Homebrew fails

### ISSUE THREAD

**Issue by ahmetb** [sorenisanerd/gotty#32]
```
brew install sorenisanerd/gotty/gotty
```
fails on Apple M1 Macbook:
```
==> Tapping sorenisanerd/gotty
Cloning into '/opt/homebrew/Library/Taps/sorenisanerd/homebrew-gotty'...
remote: Enumerating objects: 69, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 69 (delta 5), reused 13 (delta 5), pack-reused 56
Receiving objects: 100% (69/69), 8.45 KiB | 8.45 MiB/s, done.
Resolving deltas: 100% (37/37), done.
Tapped 1 formula (14 files, 16.4KB).
gotty: The intel architecture is required for this software.
Error: gotty: An unsatisfied requirement failed this build.
```

however, Apple has a compatibility layer called Rosetta and it can actually run x86 binaries on ARM. I assume most developers enable this.

e.g. if I do `go install github.com/sorenisanerd/gotty@latest` (I think you should consider changing the command in the README to this), `gotty` works just fine on my machine. So Homebrew is being extra defensive here for no reason.

**Comment by sorenisanerd** [comment]
This should be fixed now. Can you check? I don't actually have a mac with homebrew, so I'm stabbing in the dark here :)

**Comment by crgimenes** [comment]
We are still having problems installing on M1, follow the brew log.

```
==> Tapping sorenisanerd/gotty
Cloning into '/opt/homebrew/Library/Taps/sorenisanerd/homebrew-gotty'...
remote: Enumerating objects: 77, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 77 (delta 8), reused 20 (delta 8), pack-reused 56
Receiving objects: 100% (77/77), 10.25 KiB | 283.00 KiB/s, done.
Resolving deltas: 100% (40/40), done.
Tapped 1 formula (14 files, 19.0KB).
==> Downloading https://github.com/sorenisanerd/gotty/releases/download/v1.4.0/gotty_1.4.0_darwin_arm64.tar.gz
curl: (22) The requested URL returned error: 404

Error: gotty: Failed to download resource "gotty"
Download failed: https://github.com/sorenisanerd/gotty/releases/download/v1.4.0/gotty_1.4.0_darwin_arm64.tar.gz
```

**Comment by sorenisanerd** [comment]
Fixed in https://github.com/sorenisanerd/homebrew-gotty/commit/663c270136c819beb66ebde13b1ffd558306d1b4
